Change license as per agreement with FSFE

diff --git a/bacula/scripts/disk-changer.in b/bacula/scripts/disk-changer.in
--- a/bacula/scripts/disk-changer.in
+++ b/bacula/scripts/disk-changer.in
@@ -6,8 +6,7 @@
 #
 #   Bacula(R) - The Network Backup Solution
 #
-#   Copyright (C) 2000-2015 Kern Sibbald
-#   Copyright (C) 2000-2014 Free Software Foundation Europe e.V.
+#   Copyright (C) 2000-2016 Kern Sibbald
 #
 #   The original author of Bacula is Kern Sibbald, with contributions
 #   from many others, a complete list can be found in the file AUTHORS.
@@ -31,7 +30,7 @@
 #    included.
 #
 #  disk-changer "changer-device" "command" "slot" "archive-device" "drive-index" "volume"
-#                   $1              $2       $3        $4               $5         $6
+#		    $1		    $2	     $3        $4		$5	   $6
 #
 # By default the autochanger has 10 Volumes and 1 Drive.
 #
@@ -41,8 +40,8 @@
 #
 # changer-device is the name of a file that overrides the default
 #   volumes and drives.  It may have:
-#        maxslot=n   where n is one based (default 10)
-#        maxdrive=m  where m is zero based (default 1 -- i.e. 2 drives)
+#	 maxslot=n   where n is one based (default 10)
+#	 maxdrive=m  where m is zero based (default 1 -- i.e. 2 drives)
 #  
 #   This code can also simulate barcodes. You simply put
 #   a list of the slots and barcodes in the "base" directory/barcodes.
@@ -86,7 +85,7 @@ wd=@working_dir@
 dbgfile="$wd/disk-changer.log"
 debug() {
     if test -f $dbgfile; then
-        echo "`date +\"%Y%m%d-%H:%M:%S\"` $*" >> $dbgfile
+	echo "`date +\"%Y%m%d-%H:%M:%S\"` $*" >> $dbgfile
     fi
 }
 
@@ -99,8 +98,8 @@ make_temp_file() {
   if test x${TMPFILE} = x; then
      TMPFILE="$wd/disk-changer.$$"
      if test -f ${TMPFILE}; then
-        echo "Temp file security problem on: ${TMPFILE}"
-        exit 1
+	echo "Temp file security problem on: ${TMPFILE}"
+	exit 1
      fi
   fi
 }
@@ -111,14 +110,14 @@ check_parm_count() {
     pCount=$1
     pCountNeed=$2
     if test $pCount -lt $pCountNeed; then
-        echo "usage: disk-changer ctl-device command [slot archive-device drive-index]"
-        echo "  Insufficient number of arguments arguments given."
-        if test $pCount -lt 2; then
-            echo "  Mimimum usage is first two arguments ..."
-        else
-            echo "  Command expected $pCountNeed arguments"
-        fi
-        exit 1
+	echo "usage: disk-changer ctl-device command [slot archive-device drive-index]"
+	echo "	Insufficient number of arguments arguments given."
+	if test $pCount -lt 2; then
+	    echo "  Mimimum usage is first two arguments ..."
+	else
+	    echo "  Command expected $pCountNeed arguments"
+	fi
+	exit 1
     fi
 }
 
@@ -131,7 +130,7 @@ get_dir() {
    dir=`echo "$device" | sed -e s%/$bn%%g`
    if [ ! -d $dir ]; then
       echo "ERROR: Autochanger directory \"$dir\" does not exist."
-      echo "       You must create it."
+      echo "	   You must create it."
       exit 1
    fi
 }
@@ -178,32 +177,32 @@ fi
 #
 case $2 in
     list|listall)
-        check_parm_count $# 2
-        ;;
+	check_parm_count $# 2
+	;;
     slots)
-        check_parm_count $# 2
-        ;;
+	check_parm_count $# 2
+	;;
     transfer)
-        check_parm_count $# 4
-        if [ $slot -gt $maxslot ]; then
-           echo "Slot ($slot) out of range (1-$maxslot)"
-           debug "Error: Slot ($slot) out of range (1-$maxslot)"
-           exit 1
-        fi
-        ;;
+	check_parm_count $# 4
+	if [ $slot -gt $maxslot ]; then
+	   echo "Slot ($slot) out of range (1-$maxslot)"
+	   debug "Error: Slot ($slot) out of range (1-$maxslot)"
+	   exit 1
+	fi
+	;;
     *)
-        check_parm_count $# 5
-        if [ $drive -gt $maxdrive ]; then
-           echo "Drive ($drive) out of range (0-$maxdrive)"
-           debug "Error: Drive ($drive) out of range (0-$maxdrive)"
-           exit 1
-        fi
-        if [ $slot -gt $maxslot ]; then
-           echo "Slot ($slot) out of range (1-$maxslot)"
-           debug "Error: Slot ($slot) out of range (1-$maxslot)"
-           exit 1
-        fi
-        ;;
+	check_parm_count $# 5
+	if [ $drive -gt $maxdrive ]; then
+	   echo "Drive ($drive) out of range (0-$maxdrive)"
+	   debug "Error: Drive ($drive) out of range (0-$maxdrive)"
+	   exit 1
+	fi
+	if [ $slot -gt $maxslot ]; then
+	   echo "Slot ($slot) out of range (1-$maxslot)"
+	   debug "Error: Slot ($slot) out of range (1-$maxslot)"
+	   exit 1
+	fi
+	;;
 esac
 
 
@@ -214,21 +213,21 @@ case $cmd in
       debug "Doing disk -f $ctl unload $slot $device $drive $volume"
       get_dir
       if [ -f $dir/loaded${drive} ]; then
-         ld=`cat $dir/loaded${drive}`
+	 ld=`cat $dir/loaded${drive}`
       else 
-         echo "Storage Element $slot is Already Full"
-         debug "Unload error: $dir/loaded${drive} is already unloaded"
-         exit 1
+	 echo "Storage Element $slot is Already Full"
+	 debug "Unload error: $dir/loaded${drive} is already unloaded"
+	 exit 1
       fi
       if [ $slot -eq $ld ]; then
-         echo "0" >$dir/loaded${drive}
-         unlink $device 2>/dev/null >/dev/null
-         unlink ${device}.add 2>/dev/null >/dev/null
-         rm -f ${device} ${device}.add
+	 echo "0" >$dir/loaded${drive}
+	 unlink $device 2>/dev/null >/dev/null
+	 unlink ${device}.add 2>/dev/null >/dev/null
+	 rm -f ${device} ${device}.add
       else
-         echo "Storage Element $slot is Already Full"
-         debug "Unload error: $dir/loaded${drive} slot=$ld is already unloaded"
-         exit 1
+	 echo "Storage Element $slot is Already Full"
+	 debug "Unload error: $dir/loaded${drive} slot=$ld is already unloaded"
+	 exit 1
       fi
       ;;
 
@@ -238,53 +237,53 @@ case $cmd in
       i=0
       # Check if slot already in a drive
       while [ $i -le $maxdrive ]; do
-         if [ -f $dir/loaded${i} ]; then
-            ld=`cat $dir/loaded${i}`
-         else    
-            ld=0
-         fi
-         if [ $ld -eq $slot ]; then
-            echo "Drive ${i} Full (Storage element ${ld} loaded)"
-            debug "Load error: Cannot load Slot=${ld} in drive=$drive. Already in drive=${i}"
-            exit 1
-         fi
-         i=`expr $i + 1`
+	 if [ -f $dir/loaded${i} ]; then
+	    ld=`cat $dir/loaded${i}`
+	 else	 
+	    ld=0
+	 fi
+	 if [ $ld -eq $slot ]; then
+	    echo "Drive ${i} Full (Storage element ${ld} loaded)"
+	    debug "Load error: Cannot load Slot=${ld} in drive=$drive. Already in drive=${i}"
+	    exit 1
+	 fi
+	 i=`expr $i + 1`
       done
       # Check if we have a Volume name
       get_vol
       if [ $havevol -eq 0 ]; then
-         # check if slot exists
-         if [ ! -f $dir/slot${slot} ] ; then
-            echo "source Element Address $slot is Empty"
-            debug "Load error: source Element Address $slot is Empty"
-            exit 1
-         fi
+	 # check if slot exists
+	 if [ ! -f $dir/slot${slot} ] ; then
+	    echo "source Element Address $slot is Empty"
+	    debug "Load error: source Element Address $slot is Empty"
+	    exit 1
+	 fi
       fi
       if [ -f $dir/loaded${drive} ]; then
-         ld=`cat $dir/loaded${drive}`
+	 ld=`cat $dir/loaded${drive}`
       else
-         ld=0
+	 ld=0
       fi
       if [ $ld -ne 0 ]; then
-         echo "Drive ${drive} Full (Storage element ${ld} loaded)"
-         echo "Load error: Drive ${drive} Full (Storage element ${ld} loaded)"
-         exit 1
+	 echo "Drive ${drive} Full (Storage element ${ld} loaded)"
+	 echo "Load error: Drive ${drive} Full (Storage element ${ld} loaded)"
+	 exit 1
       fi
       echo "0" >$dir/loaded${drive}
       unlink $device 2>/dev/null >/dev/null
       unlink ${device}.add 2>/dev/null >/dev/null
       rm -f ${device} ${device}.add
       if [ $havevol -ne 0 ]; then
-         ln -s $dir/$volume $device
-         ln -s $dir/${volume}.add ${device}.add
-         rtn=$?
+	 ln -s $dir/$volume $device
+	 ln -s $dir/${volume}.add ${device}.add
+	 rtn=$?
       else
-         ln -s $dir/slot${slot} $device
-         ln -s $dir/slot${slot}.add ${device}.add
-         rtn=$?
+	 ln -s $dir/slot${slot} $device
+	 ln -s $dir/slot${slot}.add ${device}.add
+	 rtn=$?
       fi
       if [ $rtn -eq 0 ]; then
-         echo $slot >$dir/loaded${drive}
+	 echo $slot >$dir/loaded${drive}
       fi
       exit $rtn
       ;;
@@ -293,20 +292,20 @@ case $cmd in
       debug "Doing disk -f $ctl -- to list volumes"
       get_dir 
       if [ -f $dir/barcodes ]; then
-         cat $dir/barcodes
+	 cat $dir/barcodes
       else
-         i=1
-         while [ $i -le $maxslot ]; do
-            slot=$i
-            volume=
-            get_vol
-            if [ $havevol -eq 0 ]; then
-               echo "$i:"
-            else
-               echo "$i:$volume"
-            fi
-            i=`expr $i + 1`
-         done
+	 i=1
+	 while [ $i -le $maxslot ]; do
+	    slot=$i
+	    volume=
+	    get_vol
+	    if [ $havevol -eq 0 ]; then
+	       echo "$i:"
+	    else
+	       echo "$i:$volume"
+	    fi
+	    i=`expr $i + 1`
+	 done
       fi
       exit 0
       ;;
@@ -317,20 +316,20 @@ case $cmd in
       debug "Doing disk -f $ctl -- to list volumes"
       get_dir 
       if [ ! -f $dir/barcodes ]; then
-          exit 0
+	  exit 0
       fi
 
       # we print drive content seen by autochanger
       # and we also remove loaded media from the barcode list
       i=0
       while [ $i -le $maxdrive ]; do
-         if [ -f $dir/loaded${i} ]; then
-             ld=`cat $dir/loaded${i}`
-             v=`awk -F: "/^$ld:/"' { print $2 }' $dir/barcodes`
-             echo "D:$i:F:$ld:$v"
-             echo "^$ld:" >> $TMPFILE
-         fi
-         i=`expr $i + 1`
+	 if [ -f $dir/loaded${i} ]; then
+	     ld=`cat $dir/loaded${i}`
+	     v=`awk -F: "/^$ld:/"' { print $2 }' $dir/barcodes`
+	     echo "D:$i:F:$ld:$v"
+	     echo "^$ld:" >> $TMPFILE
+	 fi
+	 i=`expr $i + 1`
       done
 
       # Empty slots are not in barcodes file
@@ -339,15 +338,15 @@ case $cmd in
       grep -v -f $TMPFILE $dir/barcodes | sort -n | \
       perl -ne 'BEGIN { $cur=1 } 
        if (/(\d+):(.+)?/) {
-         if ($cur == $1) { 
-           print "S:$1:F:$2\n" 
-         } else { 
-           while ($cur < $1) {
-              print "S:$cur:E\n";
-              $cur++;
-           }
-         }
-         $cur++;
+	 if ($cur == $1) { 
+	   print "S:$1:F:$2\n" 
+	 } else { 
+	   while ($cur < $1) {
+	      print "S:$cur:E\n";
+	      $cur++;
+	   }
+	 }
+	 $cur++;
        } 
        END { while ($cur < '"$maxslot"') { print "S:$cur:E\n"; $cur++; } } '
 
@@ -360,12 +359,12 @@ case $cmd in
       make_temp_file
       slotdest=$device
       if [ -f $dir/slot{$slotdest} ]; then
-         echo "destination Element Address $slot is Full"
-         exit 1
+	 echo "destination Element Address $slot is Full"
+	 exit 1
       fi
       if [ ! -f $dir/slot${slot} ] ; then
-         echo "source Element Address $slot is Empty"
-         exit 1
+	 echo "source Element Address $slot is Empty"
+	 exit 1
       fi
 
       echo "Transfering $slot to $slotdest"
@@ -373,8 +372,8 @@ case $cmd in
       mv $dir/slot${slot}.add $dir/slot{$slotdest}.add
 
       if [ -f $dir/barcodes ]; then
-         sed "s/^$slot:/$slotdest:/" >  $TMPFILE
-         sort -n $TMPFILE > $dir/barcodes
+	 sed "s/^$slot:/$slotdest:/" >	$TMPFILE
+	 sort -n $TMPFILE > $dir/barcodes
       fi
       exit 0
       ;;
@@ -382,9 +381,9 @@ case $cmd in
       debug "Doing disk -f $ctl $drive -- to find what is loaded"
       get_dir
       if [ -f $dir/loaded${drive} ]; then
-         a=`cat $dir/loaded${drive}`
+	 a=`cat $dir/loaded${drive}`
       else
-         a="0"
+	 a="0"
       fi
       debug "Loaded: drive=$drive is $a"
       echo $a
diff --git a/bacula/scripts/mtx-changer.in b/bacula/scripts/mtx-changer.in
--- a/bacula/scripts/mtx-changer.in
+++ b/bacula/scripts/mtx-changer.in
@@ -2,8 +2,7 @@
 #
 #   Bacula(R) - The Network Backup Solution
 #
-#   Copyright (C) 2000-2015 Kern Sibbald
-#   Copyright (C) 2000-2014 Free Software Foundation Europe e.V.
+#   Copyright (C) 2000-2016 Kern Sibbald
 #
 #   The original author of Bacula is Kern Sibbald, with contributions
 #   from many others, a complete list can be found in the file AUTHORS.
@@ -27,7 +26,7 @@
 #    in come cases, not all are used.
 #
 #  mtx-changer "changer-device" "command" "slot" "archive-device" "drive-index"
-#                  $1              $2       $3        $4               $5
+#		   $1		   $2	    $3	      $4	       $5
 #
 #  for example:
 #
@@ -38,13 +37,13 @@
 #   is /dev/nst0.
 #
 #  The commands are:
-#      Command            Function
-#      unload             unload a given slot
-#      load               load a given slot
-#      loaded             which slot is loaded?
-#      list               list Volume names (requires barcode reader)
-#      slots              how many slots total?
-#      listall            list all info
+#      Command		  Function
+#      unload		  unload a given slot
+#      load		  load a given slot
+#      loaded		  which slot is loaded?
+#      list		  list Volume names (requires barcode reader)
+#      slots		  how many slots total?
+#      listall		  list all info
 #      transfer
 #
 #  Slots are numbered from 1 ...
@@ -89,7 +88,7 @@ fi
 dbgfile="@working_dir@/mtx.log"
 debug() {
     if test -f $dbgfile -a ${debug_level} -ge $1; then
-        echo "`date +%m%d-%H:%M:%S.%N|cut -c1-16` ${chgr_id} $2" >> $dbgfile
+	echo "`date +%m%d-%H:%M:%S.%N|cut -c1-16` ${chgr_id} $2" >> $dbgfile
     fi
 }
 
@@ -102,8 +101,8 @@ make_temp_file() {
   if test x${TMPFILE} = x; then
      TMPFILE="@working_dir@/mtx.$$"
      if test -f ${TMPFILE}; then
-        echo "ERROR: Temp file security problem on: ${TMPFILE}"
-        exit 1
+	echo "ERROR: Temp file security problem on: ${TMPFILE}"
+	exit 1
      fi
   fi
 }
@@ -124,8 +123,8 @@ make_err_file() {
   if test x${ERRFILE} = x; then
      ERRFILE="@working_dir@/mtx.err.$$"
      if test -f ${ERRFILE}; then
-        echo "ERROR: Temp file security problem on: ${ERRFILE}"
-        exit 1
+	echo "ERROR: Temp file security problem on: ${ERRFILE}"
+	exit 1
      fi
   fi
 }
@@ -160,14 +159,14 @@ check_parm_count() {
     pCount=$1
     pCountNeed=$2
     if test $pCount -lt $pCountNeed; then
-        echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
-        echo "  Insufficient number of arguments given."
-        if test $pCount -lt 2; then
-            echo "  Mimimum usage is first two arguments ..."
-        else
-            echo "  Command expected $pCountNeed arguments"
-        fi
-        exit 1
+	echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
+	echo "	Insufficient number of arguments given."
+	if test $pCount -lt 2; then
+	    echo "  Mimimum usage is first two arguments ..."
+	else
+	    echo "  Command expected $pCountNeed arguments"
+	fi
+	exit 1
     fi
 }
 
@@ -176,17 +175,17 @@ check_parm_count() {
 #
 case $2 in
     list|listall)
-        check_parm_count $# 2
-        ;;
+	check_parm_count $# 2
+	;;
     slots)
-        check_parm_count $# 2
-        ;;
+	check_parm_count $# 2
+	;;
     transfer)
-        check_parm_count $# 4
-        ;;
+	check_parm_count $# 4
+	;;
     *)
-        check_parm_count $# 5
-        ;;
+	check_parm_count $# 5
+	;;
 esac
 
 
@@ -203,29 +202,29 @@ case $cmd in
    unload)
 
       if test ${offline} -eq 1 ; then
-        mt -f $device offline
+	mt -f $device offline
       fi
       if test ${offline_sleep} -ne 0 ; then
-        sleep ${offline_sleep}
+	sleep ${offline_sleep}
       fi
       make_err_file
       for i in 1 2 3 4 5 ; do
-         debug $idbglvl "Doing mtx -f $ctl unload slot=$slot drv=$drive"
-         ${MTX} -f $ctl unload $slot $drive 2>${ERRFILE}
-         rtn=$?
-         if test $rtn -eq 0 ; then
-            break
-         fi
-         grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
-         if test $? -ne 0 ; then
-            break
-         fi
-         sleep $i
+	 debug $idbglvl "Doing mtx -f $ctl unload slot=$slot drv=$drive"
+	 ${MTX} -f $ctl unload $slot $drive 2>${ERRFILE}
+	 rtn=$?
+	 if test $rtn -eq 0 ; then
+	    break
+	 fi
+	 grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
+	 if test $? -ne 0 ; then
+	    break
+	 fi
+	 sleep $i
       done
       cat ${ERRFILE}
       rm -f ${ERRFILE} >/dev/null 2>&1
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl unload slot=$slot drv=$drive"
+	 debug $idbglvl "FAIL: mtx -f $ctl unload slot=$slot drv=$drive"
       fi
       exit $rtn
       ;;
@@ -233,26 +232,26 @@ case $cmd in
    load)
       make_err_file
       for i in 1 2 3 4 5 ; do
-         debug $idbglvl "Doing mtx -f $ctl load slot=$slot drv=$drive"
-         ${MTX} -f $ctl load $slot $drive 2>${ERRFILE}
-         rtn=$?
-         if test $rtn -eq 0 ; then
-            break
-         fi
-         grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
-         if test $? -ne 0 ; then
-            break
-         fi
-         sleep $i
+	 debug $idbglvl "Doing mtx -f $ctl load slot=$slot drv=$drive"
+	 ${MTX} -f $ctl load $slot $drive 2>${ERRFILE}
+	 rtn=$?
+	 if test $rtn -eq 0 ; then
+	    break
+	 fi
+	 grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
+	 if test $? -ne 0 ; then
+	    break
+	 fi
+	 sleep $i
       done
       if test ${load_sleep} -ne 0 ; then
-        sleep ${load_sleep}
+	sleep ${load_sleep}
       fi
       wait_for_drive $device
       cat ${ERRFILE}
       rm -f ${ERRFILE} >/dev/null 2>&1
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl load slot=$slot drv=$drive"
+	 debug $idbglvl "FAIL: mtx -f $ctl load slot=$slot drv=$drive"
       fi
       exit $rtn
       ;;
@@ -260,43 +259,43 @@ case $cmd in
    list) 
       make_temp_file
       if test ${inventory} -ne 0 ; then
-        ${MTX} -f $ctl inventory
+	${MTX} -f $ctl inventory
       fi
       debug $dbglvl "Doing mtx -f $ctl list"
       ${MTX} -f $ctl status >${TMPFILE}
       rtn=$?
       if test ${vxa_packetloader} -ne 0 ; then
-        cat ${TMPFILE} | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
+	cat ${TMPFILE} | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
       else
-        cat ${TMPFILE} | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
+	cat ${TMPFILE} | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
       fi
       cat ${TMPFILE} | grep "^Data Transfer Element [0-9]*:Full (Storage Element [0-9]" | awk '{printf "%s:%s\n",$7,$10}'
       rm -f ${TMPFILE} >/dev/null 2>&1
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl list"
+	 debug $idbglvl "FAIL: mtx -f $ctl list"
       fi
       exit $rtn
       ;;
 
    listall)
-#  Drive content:         D:Drive num:F:Slot loaded:Volume Name
+#  Drive content:	  D:Drive num:F:Slot loaded:Volume Name
 #  D:0:F:2:vol2        or D:Drive num:E
 #  D:1:F:42:vol42   
 #  D:3:E
 # 
 #  Slot content:
-#  S:1:F:vol1             S:Slot num:F:Volume Name
-#  S:2:E               or S:Slot num:E
+#  S:1:F:vol1		  S:Slot num:F:Volume Name
+#  S:2:E	       or S:Slot num:E
 #  S:3:F:vol4
 # 
 #  Import/Export tray slots:
-#  I:10:F:vol10           I:Slot num:F:Volume Name
-#  I:11:E              or I:Slot num:E
+#  I:10:F:vol10 	  I:Slot num:F:Volume Name
+#  I:11:E	       or I:Slot num:E
 #  I:12:F:vol40
  
       make_temp_file
       if test ${inventory} -ne 0 ; then
-        ${MTX} -f $ctl inventory
+	${MTX} -f $ctl inventory
       fi
       debug $dbglvl "Doing mtx -f $ctl -- to list all"
       ${MTX} -f $ctl status >${TMPFILE}
@@ -324,7 +323,7 @@ case $cmd in
       ${MTX} -f $ctl transfer $slot $slotdest
       rtn=$?
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl transfer from=$slot to=$slotdest"
+	 debug $idbglvl "FAIL: mtx -f $ctl transfer from=$slot to=$slotdest"
       fi
       exit $rtn
       ;;
@@ -338,7 +337,7 @@ case $cmd in
       cat ${TMPFILE} | grep "^Data Transfer Element $drive:Empty" | awk "{print 0}"
       rm -f ${TMPFILE} >/dev/null 2>&1
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl loaded drv=$drive"
+	 debug $idbglvl "FAIL: mtx -f $ctl loaded drv=$drive"
       fi
       exit $rtn
       ;;
@@ -348,7 +347,7 @@ case $cmd in
       ${MTX} -f $ctl status | grep " *Storage Changer" | awk "{print \$5}"
       rtn=$?
       if test $rtn -ne 0 ; then
-         debug $idbglvl "FAIL: mtx -f $ctl slots"
+	 debug $idbglvl "FAIL: mtx -f $ctl slots"
       fi
       ;;
 esac
