Backport from Bacula Enterprise

diff --git a/bacula/scripts/mtx-changer.in b/bacula/scripts/mtx-changer.in
--- a/bacula/scripts/mtx-changer.in
+++ b/bacula/scripts/mtx-changer.in
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Bacula interface to mtx autoloader
+#   Bacula(R) - The Network Backup Solution
 #
-#  Written by Kern Sibbald
+#   Copyright (C) 2000-2015 Kern Sibbald
+#   Copyright (C) 2000-2014 Free Software Foundation Europe e.V.
 #
-#  Bacula® - The Network Backup Solution
+#   The original author of Bacula is Kern Sibbald, with contributions
+#   from many others, a complete list can be found in the file AUTHORS.
 #
-#  Copyright (C) 2000-2014 Free Software Foundation Europe e.V.
+#   You may use this file and others of this release according to the
+#   license defined in the LICENSE file, which includes the Affero General
+#   Public License, v3.0 ("AGPLv3") and some additional permissions and
+#   terms pursuant to its AGPLv3 Section 7.
 #
-#  The main author of Bacula is Kern Sibbald, with contributions from many
-#  others, a complete list can be found in the file AUTHORS.
+#   This notice must be preserved when any source code is 
+#   conveyed and/or propagated.
 #
-#  You may use this file and others of this release according to the
-#  license defined in the LICENSE file, which includes the GNU Lesser
-#  General Public License, v3.0 ("LGPLv3") and some additional permissions and
-#  terms pursuant to its LGPLv3 Section 7.
-#
-#  Bacula® is a registered trademark of Kern Sibbald.
+#   Bacula(R) is a registered trademark of Kern Sibbald.
 #
 #  If you set in your Device resource
 #
@@ -27,24 +27,24 @@
 #    in come cases, not all are used.
 #
 #  mtx-changer "changer-device" "command" "slot" "archive-device" "drive-index"
-#		   $1		   $2	    $3	      $4	       $5
+#                  $1              $2       $3        $4               $5
 #
 #  for example:
 #
 #  mtx-changer /dev/sg0 load 1 /dev/nst0 0 (on a Linux system)
-#
+# 
 #  will request to load the first cartidge into drive 0, where
 #   the SCSI control channel is /dev/sg0, and the read/write device
 #   is /dev/nst0.
 #
 #  The commands are:
-#      Command		  Function
-#      unload		  unload a given slot
-#      load		  load a given slot
-#      loaded		  which slot is loaded?
-#      list		  list Volume names (requires barcode reader)
-#      slots		  how many slots total?
-#      listall		  list all info
+#      Command            Function
+#      unload             unload a given slot
+#      load               load a given slot
+#      loaded             which slot is loaded?
+#      list               list Volume names (requires barcode reader)
+#      slots              how many slots total?
+#      listall            list all info
 #      transfer
 #
 #  Slots are numbered from 1 ...
@@ -57,10 +57,13 @@
 #  Many changers need an offline after the unload. Also many
 #   changers need a sleep 60 after the mtx load.
 #
-#  N.B. If you change the script, take care to return either
+#  N.B. If you change the script, take care to return either 
 #   the mtx exit code or a 0. If the script exits with a non-zero
 #   exit code, Bacula will assume the request failed.
 #
+
+# myversion must be the same as version in mtx-changer.conf
+myversion=2
 
 # source our conf file
 if test ! -f @scriptdir@/mtx-changer.conf ; then
@@ -71,6 +74,13 @@ if test ! -f @scriptdir@/mtx-changer.conf ; then
 fi
 . @scriptdir@/mtx-changer.conf
 
+if test "${version}" != "${myversion}" ; then
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  echo "ERROR: @scriptdir@/mtx-changer.conf has wrong version. Wanted ${myversion}, got ${version} !!!"
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  exit 1
+fi
+
 MTX=@MTX@
 
 if test ${debug_log} -ne 0 ; then
@@ -78,8 +88,8 @@ if test ${debug_log} -ne 0 ; then
 fi
 dbgfile="@working_dir@/mtx.log"
 debug() {
-    if test -f $dbgfile; then
-	echo "`date +\"%Y%m%d-%H:%M:%S\"` $*" >> $dbgfile
+    if test -f $dbgfile -a ${debug_level} -ge $1; then
+        echo "`date +%m%d-%H:%M:%S.%N|cut -c1-16` ${chgr_id} $2" >> $dbgfile
     fi
 }
 
@@ -92,8 +102,8 @@ make_temp_file() {
   if test x${TMPFILE} = x; then
      TMPFILE="@working_dir@/mtx.$$"
      if test -f ${TMPFILE}; then
-	echo "ERROR: Temp file security problem on: ${TMPFILE}"
-	exit 1
+        echo "ERROR: Temp file security problem on: ${TMPFILE}"
+        exit 1
      fi
   fi
 }
@@ -107,22 +117,22 @@ make_temp_file() {
 #  So we separate STDOUT and STDERR in
 #  certain of the mtx commands. The contents of STDERR
 #  is then printed after the STDOUT produced by mtx
-#  thus we sometimes get better changer results.
+#  thus we sometimes get better changer results. 
 #
 make_err_file() {
   ERRFILE=`mktemp @working_dir@/mtx.err.XXXXXXXXXX`
   if test x${ERRFILE} = x; then
      ERRFILE="@working_dir@/mtx.err.$$"
      if test -f ${ERRFILE}; then
-	echo "ERROR: Temp file security problem on: ${ERRFILE}"
-	exit 1
+        echo "ERROR: Temp file security problem on: ${ERRFILE}"
+        exit 1
      fi
   fi
 }
 
 
 #
-# The purpose of this function to wait a maximum
+# The purpose of this function to wait a maximum 
 #   time for the drive. It will
 #   return as soon as the drive is ready, or after
 #   waiting a maximum of 300 seconds.
@@ -133,12 +143,12 @@ make_err_file() {
 #   in the code at the top of this script.
 #
 wait_for_drive() {
-  i=0
+  i=0 
   while [ $i -le 300 ]; do  # Wait max 300 seconds
     if mt -f $1 status 2>&1 | grep "${ready}" >/dev/null 2>&1; then
       break
     fi
-    debug "Device $1 - not ready, retrying..."
+    debug $dbglvl "Device $1 - not ready, retrying..."
     sleep 1
     i=`expr $i + 1`
   done
@@ -150,33 +160,33 @@ check_parm_count() {
     pCount=$1
     pCountNeed=$2
     if test $pCount -lt $pCountNeed; then
-	echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
-	echo "	Insufficient number of arguments given."
-	if test $pCount -lt 2; then
-	    echo "  Mimimum usage is first two arguments ..."
-	else
-	    echo "  Command expected $pCountNeed arguments"
-	fi
-	exit 1
+        echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
+        echo "  Insufficient number of arguments given."
+        if test $pCount -lt 2; then
+            echo "  Mimimum usage is first two arguments ..."
+        else
+            echo "  Command expected $pCountNeed arguments"
+        fi
+        exit 1
     fi
 }
 
-# Check for special cases where only 2 arguments are needed,
+# Check for special cases where only 2 arguments are needed, 
 #  all others are a minimum of 5
 #
 case $2 in
     list|listall)
-	check_parm_count $# 2
-	;;
+        check_parm_count $# 2
+        ;;
     slots)
-	check_parm_count $# 2
-	;;
+        check_parm_count $# 2
+        ;;
     transfer)
-	check_parm_count $# 4
-	;;
+        check_parm_count $# 4
+        ;;
     *)
-	check_parm_count $# 5
-	;;
+        check_parm_count $# 5
+        ;;
 esac
 
 
@@ -187,79 +197,108 @@ slot=$3
 device=$4
 drive=$5
 
-debug "Parms: $ctl $cmd $slot $device $drive"
+debug $dbglvl "Parms: $ctl $cmd $slot $device $drive"
 
-case $cmd in
+case $cmd in 
    unload)
-      debug "Doing mtx -f $ctl unload $slot $drive"
 
       if test ${offline} -eq 1 ; then
-	mt -f $device offline
+        mt -f $device offline
       fi
       if test ${offline_sleep} -ne 0 ; then
-	sleep ${offline_sleep}
+        sleep ${offline_sleep}
       fi
       make_err_file
-      ${MTX} -f $ctl unload $slot $drive 2>${ERRFILE}
-      rtn=$?
+      for i in 1 2 3 4 5 ; do
+         debug $idbglvl "Doing mtx -f $ctl unload slot=$slot drv=$drive"
+         ${MTX} -f $ctl unload $slot $drive 2>${ERRFILE}
+         rtn=$?
+         if test $rtn -eq 0 ; then
+            break
+         fi
+         grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
+         if test $? -ne 0 ; then
+            break
+         fi
+         sleep $i
+      done
       cat ${ERRFILE}
       rm -f ${ERRFILE} >/dev/null 2>&1
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl unload slot=$slot drv=$drive"
+      fi
       exit $rtn
       ;;
 
    load)
-      debug "Doing mtx -f $ctl load $slot $drive"
       make_err_file
-      ${MTX} -f $ctl load $slot $drive 2>${ERRFILE}
-      rtn=$?
+      for i in 1 2 3 4 5 ; do
+         debug $idbglvl "Doing mtx -f $ctl load slot=$slot drv=$drive"
+         ${MTX} -f $ctl load $slot $drive 2>${ERRFILE}
+         rtn=$?
+         if test $rtn -eq 0 ; then
+            break
+         fi
+         grep "Error Code=" ${ERRFILE} 2>/dev/null 1>/dev/null
+         if test $? -ne 0 ; then
+            break
+         fi
+         sleep $i
+      done
       if test ${load_sleep} -ne 0 ; then
-	sleep ${load_sleep}
+        sleep ${load_sleep}
       fi
       wait_for_drive $device
       cat ${ERRFILE}
       rm -f ${ERRFILE} >/dev/null 2>&1
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl load slot=$slot drv=$drive"
+      fi
       exit $rtn
       ;;
 
-   list)
-      debug "Doing mtx -f $ctl -- to list volumes"
+   list) 
       make_temp_file
       if test ${inventory} -ne 0 ; then
-	${MTX} -f $ctl inventory
+        ${MTX} -f $ctl inventory
       fi
+      debug $dbglvl "Doing mtx -f $ctl list"
       ${MTX} -f $ctl status >${TMPFILE}
       rtn=$?
       if test ${vxa_packetloader} -ne 0 ; then
-	cat ${TMPFILE} | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
+        cat ${TMPFILE} | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
       else
-	cat ${TMPFILE} | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
+        cat ${TMPFILE} | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
       fi
       cat ${TMPFILE} | grep "^Data Transfer Element [0-9]*:Full (Storage Element [0-9]" | awk '{printf "%s:%s\n",$7,$10}'
       rm -f ${TMPFILE} >/dev/null 2>&1
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl list"
+      fi
       exit $rtn
       ;;
 
    listall)
-#  Drive content:	  D:Drive num:F:Slot loaded:Volume Name
+#  Drive content:         D:Drive num:F:Slot loaded:Volume Name
 #  D:0:F:2:vol2        or D:Drive num:E
-#  D:1:F:42:vol42
+#  D:1:F:42:vol42   
 #  D:3:E
-#
+# 
 #  Slot content:
-#  S:1:F:vol1		  S:Slot num:F:Volume Name
-#  S:2:E	       or S:Slot num:E
+#  S:1:F:vol1             S:Slot num:F:Volume Name
+#  S:2:E               or S:Slot num:E
 #  S:3:F:vol4
-#
+# 
 #  Import/Export tray slots:
-#  I:10:F:vol10 	  I:Slot num:F:Volume Name
-#  I:11:E	       or I:Slot num:E
+#  I:10:F:vol10           I:Slot num:F:Volume Name
+#  I:11:E              or I:Slot num:E
 #  I:12:F:vol40
-
-      debug "Doing mtx -f $ctl -- to list all"
+ 
       make_temp_file
       if test ${inventory} -ne 0 ; then
-	${MTX} -f $ctl inventory
+        ${MTX} -f $ctl inventory
       fi
+      debug $dbglvl "Doing mtx -f $ctl -- to list all"
       ${MTX} -f $ctl status >${TMPFILE}
       rtn=$?
       # can be converted to awk+sed+cut, see below
@@ -273,7 +312,7 @@ case $cmd in
       # If perl isn't installed, you can use by those commands
 #cat ${TMPFILE} | grep "Data Transfer Element" | awk "{print \"D:\"\$4 \$7 \$9 \$10}" | sed "s/=/:/" | sed "s/Full/F:/" | sed "s/Empty/E/"
 #cat ${TMPFILE} | grep -v "Data Transfer Element" | grep "Storage Element" | grep -v "IMPORT/EXPORT" | awk "{print \"S:\"\$3 \$4 \$5}" | sed "s/IMPORT\/EXPORT//" | sed "s/Full *:VolumeTag=/F:/" | sed "s/Empty/E/"
-#cat ${TMPFILE} | grep -v "Data Transfer Element" | grep "Storage Element" | grep "IMPORT/EXPORT" | awk "{print \"I:\"\$3 \$4 \$5}" | sed "s/IMPORT\/EXPORT//" | sed "s/Full *:VolumeTag=/F:/" | sed "s/Empty/E/"
+#cat ${TMPFILE} | grep -v "Data Transfer Element" | grep "Storage Element" | grep "IMPORT/EXPORT" | awk "{print \"I:\"\$3 \$4 \$5}" | sed "s/IMPORT\/EXPORT//" | sed "s/Full *:VolumeTag=/F:/" | sed "s/Empty/E/" 
 
       rm -f ${TMPFILE} >/dev/null 2>&1
       exit $rtn
@@ -281,25 +320,35 @@ case $cmd in
 
    transfer)
       slotdest=$device
-      debug "Doing transfer from $slot to $slotdest"
+      debug $dbglvl "Doing transfer from $slot to $slotdest"
       ${MTX} -f $ctl transfer $slot $slotdest
       rtn=$?
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl transfer from=$slot to=$slotdest"
+      fi
       exit $rtn
       ;;
 
    loaded)
-      debug "Doing mtx -f $ctl $drive -- to find what is loaded"
       make_temp_file
+      debug $idbglvl "Doing mtx -f $ctl $drive -- to find what is loaded"
       ${MTX} -f $ctl status >${TMPFILE}
       rtn=$?
       cat ${TMPFILE} | grep "^Data Transfer Element $drive:Full" | awk "{print \$7}"
       cat ${TMPFILE} | grep "^Data Transfer Element $drive:Empty" | awk "{print 0}"
       rm -f ${TMPFILE} >/dev/null 2>&1
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl loaded drv=$drive"
+      fi
       exit $rtn
       ;;
 
    slots)
-      debug "Doing mtx -f $ctl -- to get count of slots"
+      debug $dbglvl "Doing mtx -f $ctl -- to get count of slots"
       ${MTX} -f $ctl status | grep " *Storage Changer" | awk "{print \$5}"
+      rtn=$?
+      if test $rtn -ne 0 ; then
+         debug $idbglvl "FAIL: mtx -f $ctl slots"
+      fi
       ;;
 esac
diff --git a/regress/run b/regress/run
--- a/regress/run
+++ b/regress/run
@@ -1,5 +1,10 @@
 #!/bin/sh
 #
+# Copyright (C) 2000-2015 Kern Sibbald
+# License: BSD 2-Clause; see file LICENSE-FOSS
+#
+
+#
 # Script to run a regression test with a time limit (in seconds)
 #  this allows the script to be killed if say the SD crashes
 #  due to an ASSERT.  Otherwise the script will hang for
@@ -11,11 +16,12 @@ if [ -f bin/timelimit ] ; then
    WARNTIME=900 KILLTIME=50 bin/timelimit $*
    if [ $? != 0 ] ; then
       echo " "
-      echo "=== Test $* timed out ==="
+      echo "=== Test $* failed ==="
       echo " "
       echo " " >>test.out
-      echo "=== Test $* timed out ===" >>test.out
+      echo "=== Test $* failed ===" >>test.out
       echo " " >>test.out
+      exit 1
    fi
 else
    nice $*
diff --git a/regress/run_multiple b/regress/run_multiple
--- a/regress/run_multiple
+++ b/regress/run_multiple
@@ -1,9 +1,21 @@
 #!/bin/sh
+#
+# Copyright (C) 2000-2015 Kern Sibbald
+# License: BSD 2-Clause; see file LICENSE-FOSS
+#
+
+if [ $# != 1 ] ; then
+  echo " "
+  echo "Missing test name ..."
+  echo "./run_multiple test/<test-name>"
+  echo " "
+  exit 1
+fi
 ./starttime
 export REGRESS_DEBUG=1
 for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ; do
   echo "$i. Doing $1 at `date +%R:%S`"
-  nice $1 >1
+  nice ./run $1 >1
   r=$?
   if [ $r -ne 0 ] ; then
      echo "Exit $r"
diff --git a/regress/scripts/functions b/regress/scripts/functions
--- a/regress/scripts/functions
+++ b/regress/scripts/functions
@@ -5,8 +5,7 @@
 
 check_encoding()
 {
-   ${bin}/bacula-dir -d50 -t -c ${conf}/bacula-dir.conf 2>&1 | grep 'Wanted SQL_ASCII, got UTF8' >/dev/null
-   if [ $? = 0 ]; then
+   if ${bin}/bacula-dir -d50 -t -c ${conf}/bacula-dir.conf 2>&1 | grep 'Wanted SQL_ASCII, got UTF8' >/dev/null ; then
        echo "Found database encoding problem, please modify the database encoding (SQL_ASCII)"
        exit 1
    fi
@@ -16,20 +15,25 @@ start_test()
 {
    check_encoding
    rm -rf ${working}/@*
-   # Turn off email
-   outf="${tmp}/sed_tmp"
-   echo "s%  mail =%# mail = %g" >${outf}
-   echo "s%  operator =%# operator =%g" >>${outf}
-   cp ${conf}/bacula-dir.conf ${tmp}/1
-   sed -f ${outf} ${tmp}/1 > ${conf}/bacula-dir.conf
-   if [ x$FORCE_SDCALLS = xyes ]; then
-      $bperl -e 'add_attribute("$conf/bacula-dir.conf", "SD Calls Client", "yes", "Client")'
-   fi   
+   variant_name=""
+
+   # If no or dummy smtp_host, use dummy email handler
+   if [ x${SMTP_HOST} = x -o x${SMTP_HOST} = xdummy ]; then
+      cp scripts/dummy_bsmtp bin/bsmtp
+      chmod 755 bin/bsmtp
+   else
+      # Deactivate all email
+      outf="${tmp}/sed_tmp"
+      echo "s%  mail =%# mail = %g" >${outf}
+      echo "s%  operator =%# operator =%g" >>${outf}
+      cp ${conf}/bacula-dir.conf ${tmp}/1
+      sed -f ${outf} ${tmp}/1 > ${conf}/bacula-dir.conf
+   fi
    ./test_starttime
    echo " "
    echo " "
-   echo " === Starting $TestName at `date +%R:%S` ==="
-   echo " === Starting $TestName at `date +%R:%S` ===" >> ${working}/log
+   echo " === Starting $TestName ${variant_name} at `date +%R:%S` ==="
+   echo " === Starting $TestName ${variant_name} at `date +%R:%S` ===" >> ${working}/log
    echo " "
    export TestName
    export zstat
@@ -155,12 +159,12 @@ get_duration()
 check_duration()
 {
    LOG=$1
-   $2
-   OP=${3-gt}
+   TIME=$2
+   OP=${3:-gt}
 
    get_duration $LOG
    if [ "$RET" -$OP "$TIME" ]; then
-       print_debug "Expect $OP than $TIME sec, get $RET"
+       print_debug "Error, got $RET $OP $TIME sec on $LOG"
        bstat=2
    fi
 }
@@ -265,6 +269,14 @@ check_two_logs()
    if test $? -eq 0; then
       bstat=2
    fi
+   # Do not check for restart jobs in restart tests
+   echo "$TestName" | grep restart.*-test > /dev/null
+   if [ $? -ne 0 ]; then
+      grep "^  Termination: .*Backup failed" ${tmp}/log1.out 2>&1 >/dev/null
+      if test $? -eq 0; then
+         bstat=3
+      fi
+   fi
    grep "^  Termination: *Restore OK" ${tmp}/log2.out 2>&1 >/dev/null
    rstat=${rstat:-$?}
    grep "^  Termination: .*Restore Error" ${tmp}/log2.out 2>&1 >/dev/null
@@ -286,8 +298,33 @@ check_two_logs()
    fi
    grep "Orphaned buffer" ${tmp}/log1.out ${tmp}/log2.out
    if test $? -eq 0; then
+      print_debug "Found orphaned buffers"
       estat=1
    fi
+}
+
+dtitle()
+{
+   if test "$debug" -eq 1 ; then
+      echo "============================================================"
+      echo $*
+      echo "============================================================"
+   fi
+}
+
+dmsg()
+{
+   test "$debug" -eq 1 && echo $*
+}
+
+check_size_interval()
+{
+   # if mi == -1 then then ignore mi (idem for ma)
+   mi=$1        
+   value=$2
+   ma=$3
+   
+   test \( -1 -eq $mi -o $mi -le $value \) -a \( -1 -eq $ma -o $value -le $ma \) 
 }
 
 check_restore_diff()
@@ -407,7 +444,7 @@ end_test()
       echo "  !!!!! $TestName failed!!! $t $d !!!!! "
       echo "     Status: zombie=$zstat backup=$bstat restore=$rstat diff=$dstat"
       echo " " >>test.out
-      echo "  !!!!! $TestName failed!!! $t %d !!!!! " >>test.out
+      echo "  !!!!! $TestName failed!!! $t $d !!!!! " >>test.out
       echo "     Status: zombie=$zstat backup=$bstat restore=$rstat diff=$dstat" >>test.out
       if [ $bstat != 0 -o $rstat != 0 ] ; then
          echo "     !!! Bad termination status       !!! "
