Add Docker Plugin for FileDaemon.
This is a File Daemon Docker Plugin which backup and restore
Docker objects including images, containers and persistent
volumes data with dedicated docker image. The plugin requires
a docker utility for compile and build. The default is to
automatically check for docker binary and if found then build
the plugin. Additionally refactor some configuration and build
procedures.

diff --git a/bacula/autoconf/configure.in b/bacula/autoconf/configure.in
--- a/bacula/autoconf/configure.in
+++ b/bacula/autoconf/configure.in
@@ -232,7 +232,6 @@ AC_SUBST(LIBTOOL_INSTALL_TARGET)
 AC_SUBST(LIBTOOL_UNINSTALL_TARGET)
 AC_SUBST(LIBTOOL_CLEAN_TARGET)
 AC_SUBST(QMAKE_LIBTOOL)
-AC_SUBST(FD_PLUGIN_DIR)
 
 dnl --------------------------------------------------
 dnl Include file handling
@@ -590,11 +589,11 @@ dnl -------------------------------------------
 AC_ARG_ENABLE(client-only,
    AC_HELP_STRING([--enable-client-only], [build client (File daemon) only @<:@default=no@:>@]),
    [
-       if test x$enableval = xyes; then
-	  build_client_only=yes
-	  db_backends="None"
-	  DB_BACKENDS="none"
-       fi
+      if test x$enableval = xyes; then
+         build_client_only=yes
+         db_backends="None"
+         DB_BACKENDS="none"
+      fi
    ]
 )
 if test x$build_client_only = xno; then
@@ -611,9 +610,9 @@ dnl -------------------------------------------
 AC_ARG_ENABLE(build-dird,
    AC_HELP_STRING([--enable-build-dird], [enable building of dird (Director) @<:@default=yes@:>@]),
    [
-       if test x$enableval = xno; then
-	  build_dird=no
-       fi
+      if test x$enableval = xno; then
+         build_dird=no
+      fi
    ]
 )
 
@@ -3022,6 +3021,40 @@ AC_CHECK_LIB(pthread, pthread_create, PTHREAD_LIB="-lpthread",
    ]
 )
 
+PLUGCONFILES=""
+
+dnl
+dnl Docker Plugin enable/disable
+dnl
+support_docker=auto
+AC_ARG_ENABLE(docker-plugin,
+   AC_HELP_STRING([--disable-docker-plugin], [disable Docker plugin support @<:@default=auto@:>@]),
+   [
+      if test x$enableval = xyes; then
+         support_docker=yes
+      elif test x$enableval = xno; then
+         support_docker=disabled
+      fi
+   ]
+)
+if test x$support_docker = xyes -o x$support_docker = xauto; then
+   AC_PATH_PROG(docker_bin_path, "docker", "no")
+   if test x$docker_bin_path != xno; then
+      FD_PLUGIN_DIR="$FD_PLUGIN_DIR src/plugins/fd/docker"
+      PLUGCONFILES="${PLUGCONFILES} src/plugins/fd/docker/Makefile"
+   else
+      if test x$support_docker = xyes; then
+         echo " "
+         echo "You enabled a Docker Plugin build but 'docker' command not found."
+         echo " "
+         exit 1
+      fi
+      support_docker=no
+   fi
+fi
+
+AC_SUBST(FD_PLUGIN_DIR)
+
 dnl
 dnl Check for headers, functions and libraries required to support
 dnl keeping readall capabilities
@@ -3421,111 +3454,112 @@ if test "x${subsysdir}" = "x${sbindir}" ; then
    exit 1
 fi
 
-
-AC_OUTPUT([autoconf/Make.common \
-	   Makefile \
-	   manpages/Makefile \
-	   scripts/btraceback \
-	   scripts/bconsole \
-	   scripts/baculabackupreport \
-	   scripts/bacula \
-	   scripts/bacula-ctl-dir \
-	   scripts/bacula-ctl-fd \
-	   scripts/bacula-ctl-sd \
-	   scripts/devel_bacula \
-	   scripts/Makefile \
-	   scripts/logrotate \
-	   scripts/mtx-changer \
-	   scripts/disk-changer \
-	   scripts/logwatch/Makefile \
-	   scripts/logwatch/logfile.bacula.conf \
-	   scripts/bat.desktop \
-	   scripts/bat.desktop.xsu \
-	   scripts/bat.desktop.consolehelper \
-	   scripts/bat.console_apps \
-	   scripts/bacula-tray-monitor.desktop \
-	   src/Makefile \
-	   src/host.h \
-	   src/console/Makefile \
-	   src/console/bconsole.conf \
-	   src/qt-console/bat.conf \
-	   src/qt-console/bat.pro \
-	   src/qt-console/bat.pro.mingw32 \
-	   src/qt-console/bat.pro.mingw64 \
-	   src/qt-console/install_conf_file \
-	   src/qt-console/tray-monitor/tray-monitor.conf \
-	   src/qt-console/tray-monitor/bacula-tray-monitor.conf \
-	   src/qt-console/tray-monitor/tray-monitor.pro \
-	   src/qt-console/tray-monitor/tray-monitor.pro.mingw32 \
-	   src/qt-console/tray-monitor/tray-monitor.pro.mingw64 \
-	   src/dird/Makefile \
-	   src/dird/bacula-dir.conf \
-	   src/lib/Makefile \
-	   src/stored/Makefile \
-	   src/stored/bacula-sd.conf \
-	   src/filed/Makefile \
-	   src/filed/bacula-fd.conf \
-	   src/cats/Makefile \
-	   src/cats/make_catalog_backup.pl \
-	   src/cats/make_catalog_backup \
-	   src/cats/delete_catalog_backup \
-	   src/cats/create_postgresql_database \
-	   src/cats/update_postgresql_tables \
-	   src/cats/make_postgresql_tables \
-	   src/cats/grant_postgresql_privileges \
-	   src/cats/drop_postgresql_tables \
-	   src/cats/drop_postgresql_database \
-	   src/cats/create_mysql_database \
-	   src/cats/update_mysql_tables \
-	   src/cats/make_mysql_tables \
-	   src/cats/grant_mysql_privileges \
-	   src/cats/drop_mysql_tables \
-	   src/cats/drop_mysql_database \
-	   src/cats/create_sqlite3_database \
-	   src/cats/update_sqlite3_tables \
-	   src/cats/make_sqlite3_tables \
-	   src/cats/grant_sqlite3_privileges \
-	   src/cats/drop_sqlite3_tables \
-	   src/cats/drop_sqlite3_database \
-	   src/cats/sqlite \
-	   src/cats/mysql \
-	   src/cats/create_bacula_database \
-	   src/cats/update_bacula_tables \
-	   src/cats/grant_bacula_privileges \
-	   src/cats/make_bacula_tables \
-	   src/cats/drop_bacula_tables \
-	   src/cats/drop_bacula_database \
-	   src/cats/install-default-backend \
-	   src/findlib/Makefile \
-	   src/tools/Makefile \
-	   src/plugins/fd/Makefile \
-	   src/plugins/sd/Makefile \
-	   src/plugins/dir/Makefile \
-	   po/Makefile.in \
-	   updatedb/update_mysql_tables \
-	   updatedb/update_sqlite3_tables \
-	   updatedb/update_postgresql_tables \
-	   updatedb/update_mysql_tables_9_to_10 \
-	   updatedb/update_sqlite3_tables_9_to_10 \
-	   updatedb/update_postgresql_tables_9_to_10 \
-	   updatedb/update_mysql_tables_10_to_11 \
-	   updatedb/update_sqlite3_tables_10_to_11 \
-	   updatedb/update_postgresql_tables_10_to_11 \
-	   updatedb/update_mysql_tables_11_to_12 \
-	   updatedb/update_sqlite3_tables_11_to_12 \
-	   updatedb/update_postgresql_tables_11_to_12 \
-	   examples/nagios/check_bacula/Makefile \
-	   platforms/rpms/redhat/bacula.spec \
-	   platforms/rpms/redhat/bacula-bat.spec \
-	   platforms/rpms/redhat/bacula-docs.spec \
-	   platforms/rpms/redhat/bacula-mtx.spec \
-	   platforms/rpms/suse/bacula.spec \
-	   platforms/rpms/suse/bacula-bat.spec \
-	   platforms/rpms/suse/bacula-docs.spec \
-	   platforms/rpms/suse/bacula-mtx.spec \
-	   $PFILES ],
-     [ ]
-)
+AC_CONFIG_FILES([
+   autoconf/Make.common \
+   Makefile \
+   manpages/Makefile \
+   scripts/btraceback \
+   scripts/bconsole \
+   scripts/baculabackupreport \
+   scripts/bacula \
+   scripts/bacula-ctl-dir \
+   scripts/bacula-ctl-fd \
+   scripts/bacula-ctl-sd \
+   scripts/devel_bacula \
+   scripts/Makefile \
+   scripts/logrotate \
+   scripts/mtx-changer \
+   scripts/disk-changer \
+   scripts/logwatch/Makefile \
+   scripts/logwatch/logfile.bacula.conf \
+   scripts/bat.desktop \
+   scripts/bat.desktop.xsu \
+   scripts/bat.desktop.consolehelper \
+   scripts/bat.console_apps \
+   scripts/bacula-tray-monitor.desktop \
+   src/Makefile \
+   src/host.h \
+   src/console/Makefile \
+   src/console/bconsole.conf \
+   src/qt-console/bat.conf \
+   src/qt-console/bat.pro \
+   src/qt-console/bat.pro.mingw32 \
+   src/qt-console/bat.pro.mingw64 \
+   src/qt-console/install_conf_file \
+   src/qt-console/tray-monitor/tray-monitor.conf \
+   src/qt-console/tray-monitor/bacula-tray-monitor.conf \
+   src/qt-console/tray-monitor/tray-monitor.pro \
+   src/qt-console/tray-monitor/tray-monitor.pro.mingw32 \
+   src/qt-console/tray-monitor/tray-monitor.pro.mingw64 \
+   src/dird/Makefile \
+   src/dird/bacula-dir.conf \
+   src/lib/Makefile \
+   src/stored/Makefile \
+   src/stored/bacula-sd.conf \
+   src/filed/Makefile \
+   src/filed/bacula-fd.conf \
+   src/cats/Makefile \
+   src/cats/make_catalog_backup.pl \
+   src/cats/make_catalog_backup \
+   src/cats/delete_catalog_backup \
+   src/cats/create_postgresql_database \
+   src/cats/update_postgresql_tables \
+   src/cats/make_postgresql_tables \
+   src/cats/grant_postgresql_privileges \
+   src/cats/drop_postgresql_tables \
+   src/cats/drop_postgresql_database \
+   src/cats/create_mysql_database \
+   src/cats/update_mysql_tables \
+   src/cats/make_mysql_tables \
+   src/cats/grant_mysql_privileges \
+   src/cats/drop_mysql_tables \
+   src/cats/drop_mysql_database \
+   src/cats/create_sqlite3_database \
+   src/cats/update_sqlite3_tables \
+   src/cats/make_sqlite3_tables \
+   src/cats/grant_sqlite3_privileges \
+   src/cats/drop_sqlite3_tables \
+   src/cats/drop_sqlite3_database \
+   src/cats/sqlite \
+   src/cats/mysql \
+   src/cats/create_bacula_database \
+   src/cats/update_bacula_tables \
+   src/cats/grant_bacula_privileges \
+   src/cats/make_bacula_tables \
+   src/cats/drop_bacula_tables \
+   src/cats/drop_bacula_database \
+   src/cats/install-default-backend \
+   src/findlib/Makefile \
+   src/tools/Makefile \
+   src/plugins/fd/Makefile \
+   src/plugins/sd/Makefile \
+   src/plugins/dir/Makefile \
+   po/Makefile.in \
+   updatedb/update_mysql_tables \
+   updatedb/update_sqlite3_tables \
+   updatedb/update_postgresql_tables \
+   updatedb/update_mysql_tables_9_to_10 \
+   updatedb/update_sqlite3_tables_9_to_10 \
+   updatedb/update_postgresql_tables_9_to_10 \
+   updatedb/update_mysql_tables_10_to_11 \
+   updatedb/update_sqlite3_tables_10_to_11 \
+   updatedb/update_postgresql_tables_10_to_11 \
+   updatedb/update_mysql_tables_11_to_12 \
+   updatedb/update_sqlite3_tables_11_to_12 \
+   updatedb/update_postgresql_tables_11_to_12 \
+   examples/nagios/check_bacula/Makefile \
+   platforms/rpms/redhat/bacula.spec \
+   platforms/rpms/redhat/bacula-bat.spec \
+   platforms/rpms/redhat/bacula-docs.spec \
+   platforms/rpms/redhat/bacula-mtx.spec \
+   platforms/rpms/suse/bacula.spec \
+   platforms/rpms/suse/bacula-bat.spec \
+   platforms/rpms/suse/bacula-docs.spec \
+   platforms/rpms/suse/bacula-mtx.spec \
+   $PLUGCONFILES \
+   $PFILES
+])
+AC_OUTPUT
 
 if test "${support_bat}" = "yes" ; then
    if test "x$QMAKE" = "xnone"; then
@@ -3628,72 +3662,74 @@ ${MAKE:-make} clean
 echo "
 Configuration on `date`:
 
-   Host:		     ${host}${post_host} -- ${DISTNAME} ${DISTVER}
-   Bacula version:	     ${BACULA} ${VERSION} (${DATE})
-   Source code location:     ${srcdir}
-   Install binaries:	     ${sbindir}
-   Install libraries:	     ${libdir}
-   Install config files:     ${sysconfdir}
-   Scripts directory:	     ${scriptdir}
-   Archive directory:	     ${archivedir}
-   Working directory:	     ${working_dir}
-   PID directory:	     ${piddir}
-   Subsys directory:	     ${subsysdir}
-   Man directory:	     ${mandir}
-   Data directory:	     ${datarootdir}
-   Plugin directory:	     ${plugindir}
-   C Compiler:		     ${CC} ${CCVERSION}
-   C++ Compiler:	     ${CXX} ${CXXVERSION}
-   Compiler flags:	     ${WCFLAGS} ${CFLAGS}
-   Linker flags:	     ${WLDFLAGS} ${LDFLAGS}
-   Libraries:		     ${LIBS}
-   Statically Linked Tools:  ${support_static_tools}
-   Statically Linked FD:     ${support_static_fd}
-   Statically Linked SD:     ${support_static_sd}
-   Statically Linked DIR:    ${support_static_dir}
-   Statically Linked CONS:   ${support_static_cons}
-   Database backends:	     ${db_backends}
-   Database port:	     ${db_port}
-   Database name:	     ${db_name}
-   Database user:	     ${db_user}
-   Database SSL options:     ${db_ssl_options}
+   Host:                      ${host}${post_host} -- ${DISTNAME} ${DISTVER}
+   Bacula version:            ${BACULA} ${VERSION} (${DATE})
+   Source code location:      ${srcdir}
+   Install binaries:          ${sbindir}
+   Install libraries:         ${libdir}
+   Install config files:      ${sysconfdir}
+   Scripts directory:         ${scriptdir}
+   Archive directory:         ${archivedir}
+   Working directory:         ${working_dir}
+   PID directory:             ${piddir}
+   Subsys directory:          ${subsysdir}
+   Man directory:             ${mandir}
+   Data directory:            ${datarootdir}
+   Plugin directory:          ${plugindir}
+   C Compiler:                ${CC} ${CCVERSION}
+   C++ Compiler:              ${CXX} ${CXXVERSION}
+   Compiler flags:            ${WCFLAGS} ${CFLAGS}
+   Linker flags:              ${WLDFLAGS} ${LDFLAGS}
+   Libraries:                 ${LIBS}
+   Statically Linked Tools:   ${support_static_tools}
+   Statically Linked FD:      ${support_static_fd}
+   Statically Linked SD:      ${support_static_sd}
+   Statically Linked DIR:     ${support_static_dir}
+   Statically Linked CONS:    ${support_static_cons}
+   Database backends:         ${db_backends}
+   Database port:             ${db_port}
+   Database name:             ${db_name}
+   Database user:             ${db_user}
+   Database SSL options:      ${db_ssl_options}
 
-   Job Output Email:	     ${job_email}
-   Traceback Email:	     ${dump_email}
-   SMTP Host Address:	     ${smtp_host}
+   Job Output Email:          ${job_email}
+   Traceback Email:           ${dump_email}
+   SMTP Host Address:         ${smtp_host}
 
-   Director Port:	     ${dir_port}
-   File daemon Port:	     ${fd_port}
-   Storage daemon Port:      ${sd_port}
+   Director Port:             ${dir_port}
+   File daemon Port:          ${fd_port}
+   Storage daemon Port:       ${sd_port}
 
-   Director User:	     ${dir_user}
-   Director Group:	     ${dir_group}
-   Storage Daemon User:      ${sd_user}
-   Storage DaemonGroup:      ${sd_group}
-   File Daemon User:	     ${fd_user}
-   File Daemon Group:	     ${fd_group}
+   Director User:             ${dir_user}
+   Director Group:            ${dir_group}
+   Storage Daemon User:       ${sd_user}
+   Storage DaemonGroup:       ${sd_group}
+   File Daemon User:          ${fd_user}
+   File Daemon Group:         ${fd_group}
 
-   Large file support:	     $largefile_support
-   Bacula conio support:     ${got_conio} ${CONS_LIBS}
-   readline support:	     ${got_readline} ${PRTREADLINE_SRC}
-   TCP Wrappers support:     ${TCPW_MSG} ${WRAPLIBS}
-   TLS support: 	     ${support_tls}
-   Encryption support:	     ${support_crypto}
-   ZLIB support:	     ${have_zlib}
-   LZO support: 	     ${have_lzo}
-   enable-smartalloc:	     ${support_smartalloc}
-   enable-lockmgr:	     ${support_lockmgr}
-   bat support: 	     ${support_bat}
-   client-only: 	     ${build_client_only}
-   build-dird:		     ${build_dird}
-   build-stored:	     ${build_stored}
-   Plugin support:	     ${have_plugins}
-   AFS support: 	     ${have_afs}
-   ACL support: 	     ${have_acl}
-   XATTR support:	     ${have_xattr}
-   systemd support:	     ${support_systemd} ${SYSTEMD_UNITDIR}
-   Batch insert enabled:     ${batch_insert_db_backends}
+   Large file support:        $largefile_support
+   Bacula conio support:      ${got_conio} ${CONS_LIBS}
+   readline support:          ${got_readline} ${PRTREADLINE_SRC}
+   TCP Wrappers support:      ${TCPW_MSG} ${WRAPLIBS}
+   TLS support:               ${support_tls}
+   Encryption support:        ${support_crypto}
+   ZLIB support:              ${have_zlib}
+   LZO support:               ${have_lzo}
+   enable-smartalloc:         ${support_smartalloc}
+   enable-lockmgr:            ${support_lockmgr}
+   bat support:               ${support_bat}
+   client-only:               ${build_client_only}
+   build-dird:                ${build_dird}
+   build-stored:              ${build_stored}
+   Plugin support:            ${have_plugins}
+   AFS support:               ${have_afs}
+   ACL support:               ${have_acl}
+   XATTR support:             ${have_xattr}
+   systemd support:           ${support_systemd} ${SYSTEMD_UNITDIR}
+   Batch insert enabled:      ${batch_insert_db_backends}
 
+   Plugins:
+   - Docker:                  ${support_docker}
   " > config.out
 
 # create a small shell script useful for support with
