BEE Backport bacula/src/cats/update_mysql_tables.in
This commit is the result of the squash of the following main commits:

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Apr 29 13:52:04 2020 +0200

    Update SQL scripts for Events table. Catalog format 1022

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Dec 6 10:19:13 2018 +0100

    Add procedure to upgrade from catalog version 16 to 1020

Author: Kern Sibbald <kern@sibbald.com>
Date:   Sat Aug 11 21:20:22 2018 +0200

    Permit catalog to contain negative FileIndexes

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Jun 21 17:04:46 2018 +0200

    Fix #3904 about MySQL 5.7 issue with Job/JobHisto:PriorJob field

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Feb 13 14:13:54 2018 +0100

    Add Pool::MaxPoolBytes to the catalog. Catalog version is now 1020

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Mar 23 10:10:58 2017 +0100

    Adapt update_bacula_tables scripts for catalog version 15

Author: Kern Sibbald <kern@sibbald.com>
Date:   Thu Dec 1 10:29:47 2016 +0100

    Fix bug 2275 Postgresql update script failure and add CloudParts in Media table

Author: Kern Sibbald <kern@sibbald.com>
Date:   Tue Oct 11 09:48:34 2016 +0200

    Add new Cloud part info to catalog - update database version to 1019

Author: Kern Sibbald <kern@sibbald.com>
Date:   Tue Aug 2 14:59:57 2016 +0200

    Fix copy/paste typo in update_mysql_tables.in reported by Marcin

Author: Kern Sibbald <kern@sibbald.com>
Date:   Mon Aug 1 17:24:28 2016 +0200

    Make update_xxx_tables script explanation clearer

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Apr 5 18:55:10 2016 +0200

    Implement FileMedia feature and FO_OFFSETS for plugin

     - Allow plugins to use the FO_OFFSETS option
     - Add SQL support in cats
     - Add bvfs commands
     - Add FileMedia handling in the Storage Daemon
     - Add use FO_OFFSETS option in test plugin
     - Add new sql scripts to configure.in
     - Update catalog version to 1018

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Feb 24 16:46:46 2015 +0100

    Upgrade catalog version to 1017

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu May 1 13:07:17 2014 +0200

    Fix #10747 about MySQL database creation/upgrade script

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Sun Nov 3 17:32:19 2013 +0100

    Add missing FileTable column on JobHisto table

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Oct 3 11:37:07 2013 +0200

    Update Catalog to 1016 and add Snapshot tables

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Aug 28 13:49:30 2013 +0200

    More work on migration scripts

     - Fix hardlink-test
     - Ensure that the mysql migration script will stop if having error

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Fri May 3 13:24:07 2013 +0200

    Cleanup update_xxxx_tables.in

    The script is now updating the schema step by step from version 12 to
    version 1015.

Author: Kern Sibbald <kern@sibbald.com>
Date:   Tue Feb 5 12:37:33 2013 +0100

    Add VolABytes to Media record + adapt Bacula code new DB version 1015

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Feb 23 11:39:53 2012 +0100

    Add update procedure from 5.2

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Feb 15 15:27:23 2012 +0100

    Update update_xxx_tables scripts for version 1014

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Mon Jan 30 13:19:07 2012 +0100

    Update update_xxx_tables to convert 12,13 to 14

diff --git a/bacula/src/cats/update_mysql_tables.in b/bacula/src/cats/update_mysql_tables.in
--- a/bacula/src/cats/update_mysql_tables.in
+++ b/bacula/src/cats/update_mysql_tables.in
@@ -1,21 +1,31 @@
 #!/bin/sh
 #
-# Copyright (C) 2000-2017 Kern Sibbald
+# Copyright (C) 2000-2020 Kern Sibbald
 # License: BSD 2-Clause; see file LICENSE-FOSS
 #
-# Shell script to update MySQL tables from Bacula Community version 
-#  5.0.x, 5.2.x, 7.0.x, 7.2.x, 7.4.x
+# Shell script to update MySQL tables from Bacula Enterprise version from 4.0.x to 12.4.x
 #
 echo " "
-echo "This script will update a Bacula MySQL database from version 12-16 to 16"
+echo "This script will update a Bacula MySQL database"
+echo " from any from version 12-15 or 1014-1021 to version 1022"
+echo " which is needed to convert from any Bacula Enterprise"
+echo " version 4.0.x or later to version 12.4.x"
+echo " or Bacula Community versions 5.0.x, 5.2.x, 7.4.x, 9.0.x or"
+echo " Enterprise versions 6.0.x, 6.2.x, 6.4.x, 6.6.x,"
+echo " 8.x, 10.0, 10.2 to Enterprise version 12.4.x"
 echo " "
-echo "Depending on the current version of your catalog,"
-echo "you may have to run this script multiple times."
+echo "Depending on the current version of your catalog, you may"
+echo " have to run this script multiple times"
 echo " "
-
 bindir=@MYSQL_BINDIR@
 PATH="$bindir:$PATH"
 db_name=@db_name@
+
+# Special trick to not do the upgrade from 1015 to 1016 with this script
+if [ "$1" = "--stop1015" ]; then
+    STOP1015=yes
+    shift			# remove this option from $*
+fi
 
 ARGS=$*
 
@@ -28,20 +38,23 @@ getVersion()
 getVersion
 
 if [ "x$DBVERSION" = x ]; then
-    echo
+    echo " "
     echo "Unable to detect database version, you can specify connection information"
     echo "on the command line."
     echo "Error. Cannot upgrade this database."
+    echo " "
     exit 1
 fi
 
-if [ "$DBVERSION" -lt 12 -o "$DBVERSION" -gt 16 ] ; then
+if [ "$DBVERSION" -lt 1014 -o "$DBVERSION" -gt 1021 ] ; then
+  if [ "$DBVERSION" -lt 12 -o "$DBVERSION" -gt 16 ] ; then
     echo " "
     echo "The existing database is version $DBVERSION !!"
-    echo "This script can only update an existing version 12-16 to version 16."
+    echo "This script can only update an existing version 12-16 or 1014-1021 database to version 1022."
     echo "Error. Cannot upgrade this database."
     echo " "
     exit 1
+  fi
 fi
 
 # For all versions, we need to create the Index on Media(StorageId)
@@ -106,20 +119,142 @@ USE ${db_name};
 
 INSERT INTO Status (JobStatus,JobStatusLong,Severity) VALUES
    ('I', 'Incomplete Job',25);
+UPDATE Version SET VersionId=1014;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables from 14 to 1014 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables from 14 to 1014 failed."
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1014 ] ; then
+    if mysql $* -f <<END-OF-DATA
+USE ${db_name};
+
 ALTER TABLE Media ADD COLUMN VolABytes BIGINT UNSIGNED DEFAULT 0;
 ALTER TABLE Media ADD COLUMN VolAPadding BIGINT UNSIGNED DEFAULT 0;
 ALTER TABLE Media ADD COLUMN VolHoleBytes BIGINT UNSIGNED DEFAULT 0;
 ALTER TABLE Media ADD COLUMN VolHoles INTEGER UNSIGNED DEFAULT 0;
-ALTER TABLE Media CHANGE VolWrites VolWrites BIGINT UNSIGNED;
+UPDATE Version SET VersionId=1015;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables from 1014 to 1015 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables from 1014 to 1015 failed."
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 15 -o "$DBVERSION" -eq 16 ]; then
+    # In version 16, the upgrade 1017-1018 is already done
+    if [ "$DBVERSION" -eq 16 ]; then
+        SKIP1018=1
+    fi
+
+    if mysql --skip-reconnect $* <<END-OF-DATA
+USE ${db_name};
+
+-- Revert the FileIndex if needed
+ALTER TABLE RestoreObject
+   MODIFY FileIndex INTEGER UNSIGNED DEFAULT 0;
+ALTER TABLE BaseFiles
+   MODIFY FileIndex INTEGER UNSIGNED DEFAULT 0;
+
+DROP INDEX JobId on File;
+DROP INDEX JobId_2 on File;
+
+CREATE TABLE file_temp (
+   FileId BIGINT UNSIGNED NOT NULL,
+   FileIndex INTEGER UNSIGNED DEFAULT 0,
+   JobId INTEGER UNSIGNED NOT NULL REFERENCES Job,
+   PathId INTEGER UNSIGNED NOT NULL REFERENCES Path,
+   Filename BLOB NOT NULL,
+   DeltaSeq SMALLINT UNSIGNED DEFAULT 0,
+   MarkId INTEGER UNSIGNED DEFAULT 0,
+   LStat TINYBLOB NOT NULL,
+   MD5 TINYBLOB
+   );
+
+INSERT INTO file_temp (FileId, FileIndex, JobId, PathId, Filename, DeltaSeq,
+		       MarkId, LStat, Md5)
+   SELECT FileId, FileIndex, JobId, PathId, Filename.Name, DeltaSeq, 
+	  MarkId, LStat, Md5
+    FROM File JOIN Filename USING (FilenameId);
+
+DROP TABLE Filename;
+DROP TABLE File;
+
+ALTER TABLE file_temp RENAME TO File;
+ALTER TABLE File ADD PRIMARY KEY (FileId);
+ALTER TABLE File MODIFY COLUMN FileId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
+CREATE INDEX JobId on File (JobId);
+CREATE INDEX JobId_2 on File (JobId, PathId, Filename(255));
+
+ALTER TABLE Media CHANGE VolWrites VolWrites BIGINT UNSIGNED DEFAULT 0;
+ALTER TABLE UnsavedFiles DROP COLUMN FilenameId;
+ALTER TABLE UnsavedFiles ADD COLUMN Filename BLOB NOT NULL;
+
+UPDATE Version SET VersionId = 1017;
+
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables from $DBVERSION to 1017 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables from $DBVERSION to 1017 failed."
+	exit 1
+    fi
+fi
+
+if [ "$STOP1015" = "" -a "$DBVERSION" -eq 1015 ]; then
+    if mysql --skip-reconnect $* <<END-OF-DATA
+USE ${db_name};
+
+DROP INDEX JobId on File;
+DROP INDEX JobId_2 on File;
+
+CREATE TABLE file_temp (
+   FileId BIGINT UNSIGNED NOT NULL,
+   FileIndex INTEGER UNSIGNED DEFAULT 0,
+   JobId INTEGER UNSIGNED NOT NULL REFERENCES Job,
+   PathId INTEGER UNSIGNED NOT NULL REFERENCES Path,
+   Filename BLOB NOT NULL,
+   DeltaSeq SMALLINT UNSIGNED DEFAULT 0,
+   MarkId INTEGER UNSIGNED DEFAULT 0,
+   LStat TINYBLOB NOT NULL,
+   MD5 TINYBLOB
+   );
+
+INSERT INTO file_temp (FileId, FileIndex, JobId, PathId, Filename, DeltaSeq,
+		       MarkId, LStat, Md5)
+   SELECT FileId, FileIndex, JobId, PathId, Filename.Name, DeltaSeq, 
+	  MarkId, LStat, Md5
+    FROM File JOIN Filename USING (FilenameId);
+
+DROP TABLE Filename;
+DROP TABLE File;
+
+ALTER TABLE file_temp RENAME TO File;
+ALTER TABLE File ADD PRIMARY KEY (FileId);
+ALTER TABLE File MODIFY COLUMN FileId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
+CREATE INDEX JobId on File (JobId);
+CREATE INDEX JobId_2 on File (JobId, PathId, Filename(255));
+
+ALTER TABLE Media CHANGE VolWrites VolWrites BIGINT UNSIGNED DEFAULT 0;
+ALTER TABLE Job ADD COLUMN FileTable CHAR(20) default 'File';
+ALTER TABLE JobHisto ADD COLUMN FileTable CHAR(20) default 'File';
+
 
 CREATE TABLE Snapshot (
   SnapshotId	  INTEGER UNSIGNED AUTO_INCREMENT,
   Name		  TINYBLOB NOT NULL,
-  JobId 	  INTEGER UNSIGNED DEFAULT 0,
-  FileSetId	  INTEGER UNSIGNED DEFAULT 0,
   CreateTDate	  BIGINT   NOT NULL,
   CreateDate	  DATETIME NOT NULL,
-  ClientId	  INTEGER UNSIGNED DEFAULT 0,
+  ClientId	  INTEGER DEFAULT 0,
   Volume	  TINYBLOB NOT NULL,
   Device	  TINYBLOB NOT NULL,
   Type		  TINYBLOB NOT NULL,
@@ -130,20 +265,78 @@ CREATE TABLE Snapshot (
 
 CREATE UNIQUE INDEX snapshot_idx ON Snapshot (Device(255), Volume(255), Name(255));
 
-CREATE INDEX jobtdate_idx on JobHisto (JobTDate);
+UPDATE Version SET VersionId = 1016;
 
-UPDATE Version SET VersionId=15;
 END-OF-DATA
     then
-	echo "Update of Bacula MySQL tables from 14 to 15 succeeded."
+	echo "Update of Bacula MySQL tables from 1015 to 1016 succeeded."
 	getVersion
     else
-	echo "Update of Bacula MySQL tables from 14 to 15 failed."
+	echo "Update of Bacula MySQL tables from 1015 to 1016 failed."
 	exit 1
     fi
 fi
 
-if [ "$DBVERSION" -eq 15 ] ; then
+if [ "$DBVERSION" -eq 1016 ] ; then
+    if mysql $* -f <<END-OF-DATA
+USE ${db_name};
+CREATE INDEX jobtdate_idx on JobHisto (JobTDate);
+ALTER TABLE Snapshot ADD COLUMN JobId INTEGER UNSIGNED DEFAULT 0;
+ALTER TABLE Snapshot ADD COLUMN FileSetId INTEGER UNSIGNED DEFAULT 0;
+UPDATE Version SET VersionId=1017;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables from 1016 to 1017 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables from 1016 to 1017 failed."
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1017 ] ; then
+    if mysql $* -f <<END-OF-DATA
+USE ${db_name};
+CREATE TABLE FileMedia
+(
+    JobId	      integer	UNSIGNED  not null,
+    FileIndex	      integer	UNSIGNED  not null,
+    MediaId	      integer	UNSIGNED  not null,
+    BlockAddress      bigint	UNSIGNED  default 0,
+    RecordNo	      integer	UNSIGNED  default 0,
+    FileOffset	      bigint	UNSIGNED  default 0,
+    INDEX (JobId, FileIndex)
+);
+UPDATE Version SET VersionId=1018;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables from 1017 to 1018 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables from 1017 to 1018 failed."
+	exit 1
+    fi
+fi
+
+# We are coming from version 16, so it's already done
+if [ "$SKIP1018" = 1 -a "$DBVERSION" -eq 1018 ]; then
+    if mysql $* -f  <<END-OF-DATA
+USE ${db_name};
+ALTER TABLE File MODIFY FileIndex INTEGER UNSIGNED DEFAULT 0;
+ALTER TABLE RestoreObject MODIFY FileIndex INTEGER UNSIGNED DEFAULT 0;
+ALTER TABLE BaseFiles MODIFY FileIndex INTEGER UNSIGNED DEFAULT 0;
+UPDATE Version SET VersionId=1019;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables 1018 to 1019 succeeded. (From 16)"
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables 1018 to 1019 failed. (From 16)"
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1018 ] ; then
     if mysql $* -f  <<END-OF-DATA
 USE ${db_name};
 ALTER TABLE BaseFiles MODIFY COLUMN BaseId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
@@ -152,8 +345,7 @@ ALTER TABLE Media ADD COLUMN VolParts INTEGER DEFAULT 0;
 ALTER TABLE Media ADD COLUMN VolCloudParts INTEGER DEFAULT 0;
 ALTER TABLE Media ADD COLUMN LastPartBytes BIGINT DEFAULT 0;
 ALTER TABLE Media ADD COLUMN CacheRetention BIGINT DEFAULT 0;
-ALTER TABLE Pool  ADD COLUMN CacheRetention BIGINT DEFAULT 0;
-
+ALTER TABLE Pool ADD COLUMN CacheRetention BIGINT DEFAULT 0;
 
 -- If you switch to MySQL 5.7
 ALTER TABLE Device ALTER COLUMN CleaningDate DROP DEFAULT;
@@ -172,85 +364,81 @@ ALTER TABLE Media	ALTER COLUMN LastWritten DROP DEFAULT;
 ALTER TABLE Media	ALTER COLUMN LabelDate DROP DEFAULT;
 ALTER TABLE Media	ALTER COLUMN InitialWrite DROP DEFAULT;
 ALTER TABLE Log 	ALTER COLUMN Time DROP DEFAULT;
-# speeds up restore selection if many files and accurate
-CREATE INDEX job_jobtdate_idx ON Job (JobTDate);
 
-ALTER TABLE Device
-   MODIFY CleaningDate DATETIME DEFAULT NULL;
-ALTER TABLE Media
-   MODIFY FirstWritten DATETIME DEFAULT NULL,
-   MODIFY LastWritten DATETIME DEFAULT NULL,
-   MODIFY LabelDate DATETIME DEFAULT NULL,
-   MODIFY InitialWrite DATETIME DEFAULT NULL;
-ALTER TABLE Job
-   MODIFY SchedTime DATETIME DEFAULT NULL,
-   MODIFY StartTime DATETIME DEFAULT NULL,
-   MODIFY EndTime DATETIME DEFAULT NULL,
-   MODIFY RealEndTime DATETIME DEFAULT NULL;
-ALTER TABLE JobHisto
-   MODIFY SchedTime DATETIME DEFAULT NULL,
-   MODIFY StartTime DATETIME DEFAULT NULL,
-   MODIFY EndTime DATETIME DEFAULT NULL,
-   MODIFY RealEndTime DATETIME DEFAULT NULL;
-ALTER TABLE LocationLog
-   MODIFY Date DATETIME DEFAULT NULL;
-ALTER TABLE CDImages
-   MODIFY LastBurn DATETIME DEFAULT NULL;
-
-UPDATE Version SET VersionId=16;
+UPDATE Version SET VersionId=1019;
 END-OF-DATA
     then
-	echo "Update of Bacula MySQL tables 15 to 16 succeeded."
+	echo "Update of Bacula MySQL tables 1018 to 1019 succeeded."
 	getVersion
     else
-	echo "Update of Bacula MySQL tables 15 to 16 failed."
+	echo "Update of Bacula MySQL tables 1018 to 1019 failed."
 	exit 1
     fi
 fi
 
-#
-# Update version 16 to be more robust for newer more 
-# strict MySQLs.  Note: this is a post-first release
-# fix.
-#
-if [ "$DBVERSION" -eq 16 ] ; then
+
+if [ "$DBVERSION" -eq 1019 ] ; then
     if mysql $* -f  <<END-OF-DATA
 USE ${db_name};
-ALTER TABLE Device
-   MODIFY CleaningDate DATETIME DEFAULT NULL;
+ALTER TABLE Pool ADD COLUMN MaxPoolBytes BIGINT UNSIGNED DEFAULT 0;
+ALTER TABLE Job ADD COLUMN PriorJob TINYBLOB;
+ALTER TABLE JobHisto ADD COLUMN PriorJob TINYBLOB;
+UPDATE Version SET VersionId=1020;
+END-OF-DATA
+    then
+	echo "Update of Bacula MySQL tables 1019 to 1020 succeeded."
+	getVersion
+    else
+	echo "Update of Bacula MySQL tables 1019 to 1020 failed."
+	exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1020 ] ; then
+    if mysql $* -f  <<END-OF-DATA
+USE ${db_name};
 ALTER TABLE File
    MODIFY FileIndex INTEGER DEFAULT 0;
 ALTER TABLE RestoreObject
    MODIFY FileIndex INTEGER DEFAULT 0;
 ALTER TABLE BaseFiles
    MODIFY FileIndex INTEGER DEFAULT 0;
-ALTER TABLE Media
-   MODIFY FirstWritten DATETIME DEFAULT NULL,
-   MODIFY LastWritten DATETIME DEFAULT NULL,
-   MODIFY LabelDate DATETIME DEFAULT NULL,
-   MODIFY InitialWrite DATETIME DEFAULT NULL;
-ALTER TABLE Job
-   MODIFY SchedTime DATETIME DEFAULT NULL,
-   MODIFY StartTime DATETIME DEFAULT NULL,
-   MODIFY EndTime DATETIME DEFAULT NULL,
-   MODIFY RealEndTime DATETIME DEFAULT NULL;
-ALTER TABLE JobHisto
-   MODIFY SchedTime DATETIME DEFAULT NULL,
-   MODIFY StartTime DATETIME DEFAULT NULL,
-   MODIFY EndTime DATETIME DEFAULT NULL,
-   MODIFY RealEndTime DATETIME DEFAULT NULL;
-ALTER TABLE LocationLog
-   MODIFY Date DATETIME DEFAULT NULL;
-ALTER TABLE CDImages
-   MODIFY LastBurn DATETIME DEFAULT NULL;
-
+UPDATE Version SET VersionId=1021;
 END-OF-DATA
     then
-	echo "Update of Bacula MySQL tables 16 to 16 succeeded."
-	getVersion
+        echo "Update of Bacula MySQL tables 1020 to 1021 succeeded."
+        getVersion
     else
-	echo "Update of Bacula MySQL tables 16 to 16 failed."
-	exit 1
+        echo "Update of Bacula MySQL tables 1020 to 1021 failed."
+        exit 1
+    fi
+fi
+
+if [ "$DBVERSION" -eq 1021 ] ; then
+    if mysql $* -f  <<END-OF-DATA
+USE ${db_name};
+CREATE TABLE Events
+(
+    EventsId          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
+    EventsCode        TINYBLOB NOT NULL,
+    EventsType        TINYBLOB NOT NULL,
+    EventsTime        DATETIME,
+    EventsInsertTime  DATETIME DEFAULT NOW(),
+    EventsDaemon        TINYBLOB NOT NULL,
+    EventsSource      TINYBLOB NOT NULL,
+    EventsRef         TINYBLOB NOT NULL,
+    EventsText        BLOB NOT NULL,
+    primary key (EventsId)
+);
+create index events_time_idx on Events (EventsTime);
+UPDATE Version SET VersionId=1022;
+END-OF-DATA
+    then
+        echo "Update of Bacula MySQL tables 1021 to 1022 succeeded."
+        getVersion
+    else
+        echo "Update of Bacula MySQL tables 1021 to 1022 failed."
+        exit 1
     fi
 fi
 
